apiVersion: v1
kind: Pod
metadata:
  name: hostpath-demo-pod
spec:
  containers:
    - name: node-app
      image: busybox
      command: ['sh', '-c', 'while true; do sleep 10; done']
      volumeMounts:
        - name: host-storage
          mountPath: /host-data
  volumes:
    - name: host-storage
      hostPath:
        path: /data/host-demo
        type: DirectoryOrCreate
