apiVersion: v1
kind: Pod
metadata:
  name: multi-container-pod
spec:
  containers:
    - name: express-app
      image: express-demo:v2
      ports:
        - containerPort: 3000

    - name: sidecar-logger
      image: busybox
      command:
        [
          'sh',
          '-c',
          "while true; do echo 'ðŸ“¢ Sidecar running inside same pod'; sleep 5; done",
        ]
