apiVersion: v1
kind: Pod
metadata:
  name: my-node-app
  labels:
    app: node-demo
spec:
  containers:
    - name: node-container
      image: node:18-alpine
      command: ['node']
      args:
        [
          '-e',
          "require('http').createServer((req,res)=>res.end('Hello from Kubernetes Pod ğŸš€')).listen(3000)",
        ]
      ports:
        - containerPort: 3000
