apiVersion: v1
kind: Service
metadata:
  name: express-service
spec:
  type: NodePort
  selector:
    app: express-demo
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
      nodePort: 32000
